#!/usr/bin/python
#This is a python script I wrote that automatically moves my Photographs to bulk storage where it is then also backed up to a server 
import shutil
import os

#Import time
#import time #commented out as they are unused 
#from datetime import datetime #commented out as they are unused 

#starting path for ingest 

path = "/home/kenny/Documents/Photography-Ingest/"

print("Copying the following files:")
print(os.listdir(path))

#setting up source and destination 

src = "/home/kenny/Documents/Photography-Ingest"

dest = "/media/storage/Buse Photography"

#shutil.copytree(src, dest, symlinks=False, dirs_exist_ok=True)
#shutil.copystat(src, dest, follow_symlinks=True)

try:
    shutil.copytree(src, dest, symlinks=False, dirs_exist_ok=True)
except shutil.SameFileError:
    pass

print("Contents of the Destination")
print(os.listdir(dest))

print("Clearing Ingest Folder")
for files in os.listdir(src):
    path2 = os.path.join(src, files)
    try:
        shutil.rmtree(path2)
    except OSError:
        os.remove(path2)

print("Listing Ingest Inventory")
print(os.listdir(src))